### ISSUE TITLE
Logging to csv

### ISSUE THREAD

**Issue by Strormcrow** [freeranger/evologger#3]
Hi! 

It's been some years since this was written, I managed to get it up and going perfectly though. The only thing I'm missing is that I can not log the outdoor-temperature to the same *.csv-file as the temperatures. 

Can someone help me?

**Comment by freeranger** [comment]
It would probably be helpful if you posted some more details about what is happening - there could be any number of reasons why you are having problems logging to the same file but you have given no details at all.
Also useful if you posted your config.ini and anything else custom to your setup, but without your private API keys/other secrets.

I haven’t worked on this for a long time so things may have moved on in the interim....

**Comment by freeranger** [comment]
Closing due to no response
