### ISSUE TITLE
cron job 

### ISSUE THREAD

**Issue by slahy** [freeranger/evologger#5]
Not sure how else to make a suggestion on github.....
to run the logger via a cron tab entry the following will start the python script at boot and all paths etc will be correct and available to the script 

@reboot cd /data/code/evologger;/usr/bin/python /data/code/evologger/evologger.py > /data/code/evologger/evohomelogging_cron.log 2>&1

paths should be updated as per your own system.

**Comment by freeranger** [comment]
Thanks @slahy - I will give it a go at some point and update the docs if I get it working - no spare cycles at the moment!
